### ISSUE TITLE
Bar graph of percentages

### ISSUE THREAD

**Issue by edvinli** [bowald/chs-exam-statistics#2]
Nice feature that you can see the percentages. Would be even more awesome if you could see them the same way as the quantiles, i.e. a bar graph! (easier to compare different years).

Keep up the good work!

**Comment by bowald** [comment]
I’ve tried the bar graph approached, however bar representation was not great for showing percentage data. It was hard to compare different results due to not knowing the quantities for a certain exam. Also reexams with a low number of participants becomes spikes, and without a quantity reference, hard to interpret.

I think the now implemented table representation allows the user to get an better overview, especially using the sorting function(clicking on a category).

If you provide a more detailed concept of a diagram representation, I can try to implement it, but I don’t think a bar diagram is the way to go.
